### ISSUE TITLE
Image tag inline with text instead of blockwise

### ISSUE THREAD

**Issue by aruntk** [open-xml-templating/docxtemplater-image-module#2] opened 2015-01-05 08:41 UTC
I'm currently using docxtemplater 0.x . Because of the condition `{%image} need to be in its own <w:p>` I'm not able to use 1.x . I want the image to be in line with text. Is it possible to fix this issue? If yes please guide me.

**Comment by edi9999** [comment] 2015-01-05 09:09
Hi @arunhedcet 

this module is only compatible with docxtemplater 1.0

I understand that you need to have your image inline with the text. At the current moment, it is not possible.

They are two ways to output images for now: normal images (https://github.com/edi9999/docxtemplater-image-module/blob/master/coffee/index.coffee#L64) and centered images (https://github.com/edi9999/docxtemplater-image-module/blob/master/coffee/index.coffee#L115)

The links are to the functions that generate the xml that is needed to show the image.

Can you maybe send what you would like to have as a result, so I can inspect the XML of that corresponding image ?

**Comment by arunhedcet** [comment] 2015-01-05 09:31
Thanks for replying. I need something like this `{#loop}{text1}{%image1}{text2}{/loop}` . Here is a sample docx. [Sample.docx](https://drive.google.com/file/d/0B_N4Uc16m5v-VUlDS0VzNGh1Zjg/view?usp=sharing) .

**Comment by edi9999** [comment] 2015-01-05 09:40
I would guess that if you don't use the centered option, it should put the image inline. Can you test this ?

**Comment by edi9999** [comment] 2015-01-05 12:16
Ok, it doesn't seem to work yet. It is not that easy to understand why

**Comment by arunhedcet** [comment] 2015-01-08 06:04
Sorry for not replying. I've tested this and its not working with text in line. Maybe if you can give me some insights on the technical part of this issue I'd like to contribute.

**Comment by edi9999** [comment] 2015-01-08 15:58
When I open the zipfile of the added test (images/imageInlineExample.docx)

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml version="1.0"?>
<w:document xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
  <w:body>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Normal"/>
        <w:rPr/>
      </w:pPr>
      <w:r>
        <w:rPr/>
        <w:t>This is an inline image {%firefox}. End of the line</w:t>
      </w:r>
    </w:p>
    <w:sectPr>
      <w:headerReference w:type="default" r:id="rId2"/>
      <w:type w:val="nextPage"/>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:left="1800" w:right="1800" w:header="720" w:top="2810" w:footer="0" w:bottom="1440" w:gutter="0"/>
      <w:pgNumType w:fmt="decimal"/>
      <w:formProt w:val="false"/>
      <w:textDirection w:val="lrTb"/>
      <w:docGrid w:type="default" w:linePitch="249" w:charSpace="2047"/>
    </w:sectPr>
  </w:body>
</w:document>
```

When the cursor is after the closing tag `...{firefox}|...`

the function `handle` is called with the arguments `("replaceTag","image")`

so this will trigger at the end a call to @replaceBy()

The problem is that I cannot replace {firefox} by something in the xml, because a <w:drawing> doesn't belong in a <w:t>

**Comment by arunhedcet** [comment] 2015-01-08 16:22
Okay. I get it. What about taking the contents inside the `<w:t>` and splitting it into different tags? (text1+drawing+text2)

**Comment by edi9999** [comment] 2015-01-08 17:36
Yes that would be the solution.

You should implement that function in docxtemplater (file xmltemplater.coffee) but that file is difficult to get into completely

**Comment by arunhedcet** [comment] 2015-01-08 17:47
I'll try.. Thanks for the help.

**Comment by edi9999** [comment] 2015-01-20 11:09
I @arunhedcet , have you found out a way to do this ?

**Comment by edi9999** [comment] 2015-03-01 13:31
Closing as stale, but feel free to reopen if it is still up to date

**Comment by edi9999** [comment] 2017-02-22 17:18
Images can now be inlined, however, you have to use this trick to make sure that the text around the image is not suppressed : 

You need to format your image tag with a different format than the paragraph that it is in.

For example you should write : 

My image is **{%image}**, yes {name}

**Closed** 2017-02-22 17:18 UTC
Labels: enhancement
