### ISSUE TITLE
v3.0.1 image in pptx TemplateError: Raw tag not in paragraph

### ISSUE THREAD

**Issue by andypeng2015** [open-xml-templating/docxtemplater-image-module#79] opened 2017-02-06 02:54 UTC
hi @edi9999 sorry for this but i tried v3.0.1 and still the same error `TemplateError: Raw tag not in paragraph`, my complete data and template attached, pls kindly take a look, thanks a lot in advance.

this template includes all the data and tags, not only the image tag

#78

**Comment by edi9999** [comment] 2017-02-06 08:04
Please share a zip file that contains the whole code to reproduce the issue : 

I would like to have : 

* index.html file
* all built files (docxtemplater, jszip, ...)
* input pptx

The code should be working on my machine without having to copy files around. downloading other files, etc...

Please share a functional zip file that can be run as is.

**Comment by edi9999** [comment] 2017-02-06 08:19
Ok, it seems they is a small bug in version 3.0.1 : 

You need to add in your code : 				opts.fileType = "pptx";

because the imageModule didn't take the fileType of the documet into account, but instead had its own option.

This option will be removed in the next version of the image module, but for now, you can just add the code that I sent

**Comment by andypeng2015** [comment] 2017-02-06 09:22
hi @edi9999 apologize for the trouble caused, really appreciate your help, now I can save the pptx file but the image in the ppt file is not displyed, do u hv the same issue on your end? thanks

![capture](https://cloud.githubusercontent.com/assets/24508594/22641258/e2ba6880-ec90-11e6-85b9-a43138aadf4d.JPG)

**Comment by edi9999** [comment] 2017-02-06 10:40
This might help : https://github.com/open-xml-templating/docxtemplater-image-module/issues/16#issuecomment-110391698

**Comment by edi9999** [comment] 2017-02-06 21:57
The original issue is fixed in version 3.0.2

**Closed by edi9999** 2017-02-06 21:57 UTC

**Comment by andypeng2015** [comment] 2017-02-07 11:16
hi @edi9999 thanks for the advise and quick fix
