### ISSUE TITLE
Dynamic image insertion

### ISSUE THREAD

**Issue by Lennyman** [open-xml-templating/docxtemplater-image-module#70] opened 2016-11-22 11:25 UTC
Hi All, I understand how to replace a tag like {%image} with an image, but what if I wanted to create a dynamic table like this:-

{#table1}{rowimg}	{field1}	{field2} {/table1}

The data would be in the form of:-
{"table1":[ {rowimg:'randomfilename.gif',field1:'Bad',field2:'Offline'}, {rowimg:'anotherrandom.gif',field1:'Good',field2:'Online'}]}

The images are 'random' for all intents and purposes (they're not, but there are 100's of them), so I need to dynamically add the images without specifying each and every one of them.

Any ideas gratefully received.

cheers, Paul.

**Comment by edi9999** [comment] 2016-11-23 08:15
It should be working by having this template : 

```
{#table1}{%rowimg}	{field1}	{field2} {/table1}
```

and having 

```
doc.setData({"table1":[ {rowimg:'randomfilename.gif',field1:'Bad',field2:'Offline'}, {rowimg:'anotherrandom.gif',field1:'Good',field2:'Online'}]})
```

What exactly is the problem you get ?

**Comment by Lennyman** [comment] 2016-11-23 10:23
Thanks for the response.

I've tried referring to the image as {rowimg:img .... } :-
img=__dirname + "\\unknown.gif";
img=__dirname + "/unknown.gif";
img="unknown.gif";

and all result in "undefined"

Is there a way of getting a meaningful error message to determine what the actual problem is?

Cheers,

Paul

**Comment by edi9999** [comment] 2016-11-23 10:38
I think the problem is in your template : 

it should be : `{%rowimg}`, and not `{rowimg}`

To get some messages, you could write : 

```
doc.setOptions({
    parser: function(tag) {
      return {
        'get': function(scope) {
          console.log('evaluating', tag, 'in', JSON.stringify(scope));
          console.log('evaluated to', scope[tag]);
          if (tag === '.') {
            return scope;
          } else {
            return scope[tag];
          }
        }
      };
    },
})
```

**Comment by Lennyman** [comment] 2016-11-23 14:42
Many thanks for the help. I thought I'd keep it simple, so this is my .docx template entry:-

> {%img}

This is the code:-

> doc.setData({img:__dirname + "\\unknown.gif"});
> doc.render();

console shows:-

> evaluating %img in {"img":"D:\\inetpub\\node\\unknown.gif"}
> evaluated to undefined

Any ideas?

**Comment by edi9999** [comment] 2016-11-23 14:52
did you attach the module ? 

`doc.attachModule(imageModule)`

See https://github.com/open-xml-templating/docxtemplater-image-module#usage

**Comment by edi9999** [comment] 2016-11-23 14:54
I think to debug, the best would be to start from the example at https://github.com/open-xml-templating/docxtemplater-image-module#usage , and then, make it search the image from your application code, then the data, until it doesn't work anymore.

**Comment by Lennyman** [comment] 2016-11-23 16:03
Ok... rookie mistake. I didn't add the module (I know.... RTFM....)

One step forward, one back. I now get (as I would expect) 

> evaluated to D:\inetpub\node\merge_templates\images\handsets\5220.gif

I added some debug to opts.getImage, and that shows:-

> tagValue=D:\inetpub\node\merge_templates\images\handsets\mitel_4025.gif
>  tagName=extnimg

So no "undefined" any more. But now I just empty cells in the table instead.... sigh....

**Comment by edi9999** [comment] 2016-11-23 16:07
Can you add the following : 

```
opts.getImage=function(tagValue, tagName) {
    var binaryData =  fs.readFileSync(tagValue,'binary');
    console.log(binaryData);
    return binaryData;
}
```

Also, can you try with a png image instead of a gif ? I'm not sure myself which formats are supported, but I know for sure that PNG is supported

**Comment by Lennyman** [comment] 2016-11-23 16:25
Ok - It's working.... sort of...

All the images get inserted, but Work throws an error before opening the document as follows:-

![image](https://cloud.githubusercontent.com/assets/124485/20569827/58f1c8f0-b199-11e6-821f-8240da6a9790.png)

![image](https://cloud.githubusercontent.com/assets/124485/20569838/6043c07c-b199-11e6-9e2e-3b96fd4a3878.png)

I press "Yes" and it does appear to insert the images:-

![image](https://cloud.githubusercontent.com/assets/124485/20569849/6bc499d0-b199-11e6-9249-e04359f072d9.png)

**Comment by Lennyman** [comment] 2016-11-23 16:26
Here is the generated document

[Report (37).docx](https://github.com/open-xml-templating/docxtemplater-image-module/files/609369/Report.37.docx)

**Comment by Lennyman** [comment] 2016-11-23 16:27
And the template I used
[Test_HLD.docx](https://github.com/open-xml-templating/docxtemplater-image-module/files/609375/Test_HLD.docx)

**Comment by edi9999** [comment] 2016-11-24 09:06
Is the Report (37).docx an already repaired document ?

I can open it without any errors on Word.

Can you send both the `Report (37).docx` before repair and after repair, so that I can analyse it ?

**Comment by Lennyman** [comment] 2016-11-24 09:11
Here is an original and 'fixed' one. I did look myself and it's difficult to see what the differences are other than the fixed on uses <w:picture> rather than <w:image> in the header.xml (I think....)

[Report (54).docx](https://github.com/open-xml-templating/docxtemplater-image-module/files/610875/Report.54.docx)
[Report (54)_broken.docx](https://github.com/open-xml-templating/docxtemplater-image-module/files/610876/Report.54._broken.docx)

**Comment by edi9999** [comment] 2016-11-29 22:46
Yes, they are some differences, but it is very difficult to tell exactly what word doesn't like in this case, it is quite a mistery to me this time...

**Comment by Lennyman** [comment] 2016-11-30 08:07
It must be something to do with the style-sheet or existing content of the document, because if I try it with a 'clean' Word doc (with or without the tokens placed in a table incidentally), it works just fine.

**Comment by Lennyman** [comment] 2016-11-30 08:09
Just a thought.... when I tried this years ago with RTF documents, I hit an issue when the index of the image I was inserting overlapped with existing inclusions. These documents have modified style-sheets with custom images for the bullets - could their inclusion be causing the issue with some conflict in the internal referenced image count etc.?

**Comment by alfonsoduarte** [comment] 2016-12-02 19:46
Hello, i have the same problem... i did everthing like 

doc.setData({"table1":[ {rowimg:'randomfilename.gif',field1:'Bad',field2:'Offline'},
{rowimg:'anotherrandom.gif',field1:'Good',field2:'Online'}]})

but only works like doc.setData({rowimg:'randomfilename.gif'}), it seems that not work inside an array.

this is my code:

var fs = Npm.require('fs');
var Docxtemplater = Npm.require('docxtemplater');
var JSZip = Npm.require('jszip');
var ImageModule = Npm.require('docxtemplater-image-module')
				
var opts = {}
      opts.centered = false;
      opts.getImage=function(tagValue, tagName) {
		var binaryData =  fs.readFileSync(tagValue,'binary');
		console.log(binaryData);
		return binaryData;
       }
		
       opts.getSize=function(img,tagValue, tagName) {
		    return [120,120];
	}
		
var imageModule=new ImageModule(opts);
var content = fs
    			.readFileSync(process.cwd() + "/gafete3.docx", "binary");
 
var zip = new JSZip(content);
var doc=new Docxtemplater()
		      .attachModule(imageModule)
   		      .loadZip(zip)
		
doc.setOptions({
		    parser: function(tag) {
		      return {
		        'get': function(scope) {
		          console.log('evaluating', tag, 'in', JSON.stringify(scope));
		          console.log('evaluated to', scope[tag]);
		          if (tag === '.') {
		            return scope;
		          } else {
		            return scope[tag];
		          }
		        }
		      };
		    },
		})
//this Works Fine
doc.setData({name:"Joan",				
                       lastName:"AAA",
                       image:process.cwd()+"/foto.png"					
});
/*this is not work with {%image} inside the template ( {#people}{name}{%image}{/peolple} )
var people = [{name:"Joan",				
                       lastName:"BBBB",
                       image:process.cwd()+"/picture1.png"},
                       {name:"Steve",				
                       lastName:"AAAA",
                       image:process.cwd()+"/picture2.png"}
                       ]
doc.setData({people});
*/
			
doc.setData({handsets});							
		
doc.render();
var buf = doc.getZip()
             	     .generate({type:"nodebuffer"});
 
fs.writeFileSync(process.cwd()+"/output.docx",buf);


Not show Error.. 
Not Show Anything, Just blank
Any ideas. :(

**Comment by Lennyman** [comment] 2016-12-05 10:07
I've tried renaming to .zip, deleting the unwanted png's from the media folder, but didn't make any difference 😢

**Comment by ranode** [comment] 2016-12-05 17:18
I have issue with including images in a table. A simple repeat works fine. But when it is included in a table, all columns other then the image column are removed. Refer output-table.docx attachment...

[output-simple.docx](https://github.com/open-xml-templating/docxtemplater-image-module/files/631792/output-simple.docx)
[input-table.docx](https://github.com/open-xml-templating/docxtemplater-image-module/files/631793/input-table.docx)
[output-table.docx](https://github.com/open-xml-templating/docxtemplater-image-module/files/631794/output-table.docx)

**Comment by edi9999** [comment] 2016-12-05 20:03
@ranode which versions of docxtemplater / docxtemplater-image-module are you using ?

**Comment by ranode** [comment] 2016-12-06 00:41
@edi9999 docxtemplater@3.0.0 doctemplater-image-module@3.0.0 node@4.6.2 Windows 8.

**Comment by edi9999** [comment] 2016-12-08 21:43
Thanks for submitting this report. This could have been fixed in docxtemplater itself, please upgrade to docxtemplater 3.0.2 and see if that helps. 

Please reopen if you still encounter the same issue

**Closed by edi9999** 2016-12-08 21:43 UTC

**Comment by ranode** [comment] 2016-12-10 05:22
@edi9999 Upgraded to 3.0.2 and it works perfect! Thank you for the quick response, and the awesome work!

**Comment by yuezhaoBJ** [comment] 2017-06-07 06:54
I also get the same error  as @Lennyman raised here. I am using 3.1.0 of docxtemplater-image-module.
The error occurred when I try to insert an image into a table cell using the {%image}.   @edi9999

**Comment by Lennyman** [comment] 2017-06-07 07:11
I did find one thing that seemed to solve it.... If you deliberately place a space between the end/start curly braces between the table and the %img tag, it seems to be far more stable, although I've not done enough testing to make it more than anecdotal. 

So from this:-
{#table1}{%rowimg}	

to this:- 
{#table1} {%rowimg}
