### ISSUE TITLE
Promises/async image loading

### ISSUE THREAD

**Issue by jskrzypek** [open-xml-templating/docxtemplater-image-module#41] opened 2016-01-27 14:38 UTC
It would be great to be able to make this module handle asynchronously loaded images, so I can do things like passing a URL for the tagValue and then have my `options.getImage()` method actually call request to `get` the image.

Happy to help you look into this if it sounds like a good thing... not sure I have the bandwidth for a whole PR just at the moment.

**Comment by edi9999** [comment] 2016-01-31 10:12
The problem is that the docxtemplater library is totally synchronous right now.
However, the xml generated by the module depends on the image (for example because of the size), so it would not be possible (eg without a hack) to do this by updating only the image-module.

But I had the idea that docxtemplater itself could handle a parser that returns promises.

Here are the steps that would make it work : (On the docxtemplater side)

 1. Load the template with JSZip (sync)
 2. Compile the template down to an easy to parse structure (sync) *
 3. Get a list of all the tags from the compiled template (sync)
 4. Resolve all values for that tag if they are promises (recursively) (async)
 5. Apply the resolved tags to the compiled template (sync)
 6. Save the file into JSZip (sync)

`*` We already use/test compilation here : https://github.com/open-xml-templating/docxtemplater/blob/6e6dc95901fca402897ce97d2a671b47560f2181/es6/docxgenTest.js#L396

Curently, we have only 1,2,5,6 . But we aren't using the compiled version to generate the tag (yet).

**Comment by edi9999** [comment] 2016-02-09 17:08
Closed in favor of https://github.com/open-xml-templating/docxtemplater/issues/195

**Closed by edi9999** 2016-02-09 17:08 UTC
